# Generated by Django 3.1 on 2020-07-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrador_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default=23, max_length=250),
            preserve_default=False,
        ),
    ]
